/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import vista.inventario;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author pc
 */
public class clientes extends javax.swing.JFrame {

    /**
     * Creates new form clientes
     */
    public clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        menu = new rojeru_san.RSButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rSButton2 = new rojeru_san.RSButton();
        rSButton3 = new rojeru_san.RSButton();
        uno = new rojeru_san.RSButton();
        rSButton4 = new rojeru_san.RSButton();
        rSButton5 = new rojeru_san.RSButton();
        rSButton6 = new rojeru_san.RSButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rSButton7 = new rojeru_san.RSButton();
        rSButton8 = new rojeru_san.RSButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "23423", "maria", "Peña", "29345345", "123 hola st"},
                { new Integer(2), "32423", "mariana", "Cruz", "23345345", "456 sogamoso St"},
                { new Integer(3), "56546", "esteban", "Grisaldo", "433453", "789 pueblo paleta St"},
                { new Integer(4), "43543", "brayan", "Perez", "1234533", "Avenida 170 Bogota"},
                { new Integer(5), "78978", "juan", "Pinzon", "34534523", "Calle 12 #33-65"}
            },
            new String [] {
                "#", "ID", "Nombre", "Apellido", "Telefono", "Direccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 790, 320));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 188, 30));

        jButton1.setText("Buscar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, 30));

        jButton5.setText("Agregar");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 89, -1, 30));

        jButton12.setText("Eliminar");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(817, 89, -1, 30));

        jPanel2.setBackground(new java.awt.Color(29, 30, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(29, 30, 51));
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        jPanel2.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 15, 47, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ESCRITORIO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 80));

        jPanel3.setBackground(new java.awt.Color(29, 30, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButton2.setBackground(new java.awt.Color(29, 30, 51));
        rSButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton2.setText("   Inventario");
        rSButton2.setColorHover(new java.awt.Color(169, 169, 169));
        rSButton2.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 260, 60));

        rSButton3.setBackground(new java.awt.Color(29, 30, 51));
        rSButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton3.setText("Caja");
        rSButton3.setColorHover(new java.awt.Color(128, 128, 128));
        rSButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 260, 60));

        uno.setBackground(new java.awt.Color(29, 30, 51));
        uno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        uno.setText("Escritorio");
        uno.setColorHover(new java.awt.Color(200, 200, 200));
        uno.setColorTextHover(new java.awt.Color(0, 0, 0));
        uno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });
        jPanel3.add(uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 260, 60));

        rSButton4.setBackground(new java.awt.Color(29, 30, 51));
        rSButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton4.setText("  Gestion de usuarios");
        rSButton4.setColorHover(new java.awt.Color(128, 128, 128));
        rSButton4.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 260, 60));

        rSButton5.setBackground(new java.awt.Color(29, 30, 51));
        rSButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton5.setText("Gestion de clientes");
        rSButton5.setColorHover(new java.awt.Color(200, 200, 200));
        rSButton5.setColorTextHover(new java.awt.Color(0, 0, 0));
        rSButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 260, 60));

        rSButton6.setBackground(new java.awt.Color(29, 30, 51));
        rSButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton6.setText("Gestion de proveedores");
        rSButton6.setColorHover(new java.awt.Color(128, 128, 128));
        rSButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 260, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("JOSE ABEL");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CARPINTERIA");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        rSButton7.setBackground(new java.awt.Color(29, 30, 51));
        rSButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton7.setText("  Gestion de pedidos");
        rSButton7.setColorHover(new java.awt.Color(128, 128, 128));
        rSButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 260, 60));

        rSButton8.setBackground(new java.awt.Color(29, 30, 51));
        rSButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rSButton8.setText("Caja");
        rSButton8.setColorHover(new java.awt.Color(128, 128, 128));
        rSButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 260, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 260, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String searchText = jTextField1.getText().trim().toLowerCase(); // Obtener el texto de búsqueda

    // Obtener el sorter de la tabla
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>((DefaultTableModel) jTable1.getModel());
    jTable1.setRowSorter(sorter);

    if (searchText.isEmpty()) {
        // Si el campo de búsqueda está vacío, mostrar todas las filas
        sorter.setRowFilter(null); // Restablecer el filtro
        return;
    }

    // Determinar la longitud del texto de búsqueda
    if (searchText.length() == 1 && Character.isDigit(searchText.charAt(0))) {
        // Si es un solo número, buscar por #
        sorter.setRowFilter(new RowFilter<DefaultTableModel, Integer>() {
            @Override
            public boolean include(RowFilter.Entry<? extends DefaultTableModel, ? extends Integer> entry) {
                String numberCellValue = entry.getStringValue(0).toLowerCase(); // Columna #
                return numberCellValue.contains(searchText);
            }
        });
    } else if (searchText.length() == 5 && searchText.chars().allMatch(Character::isDigit)) {
        // Si son 5 números, buscar por ID
        sorter.setRowFilter(new RowFilter<DefaultTableModel, Integer>() {
            @Override
            public boolean include(RowFilter.Entry<? extends DefaultTableModel, ? extends Integer> entry) {
                String idCellValue = entry.getStringValue(1).toLowerCase(); // Columna ID
                return idCellValue.contains(searchText);
            }
        });
    } else {
        // Si no coincide con las condiciones anteriores, buscar en las columnas de material, tipo y estado
        sorter.setRowFilter(new RowFilter<DefaultTableModel, Integer>() {
            @Override
            public boolean include(RowFilter.Entry<? extends DefaultTableModel, ? extends Integer> entry) {
                String nombre = entry.getStringValue(2).toLowerCase(); // Columna de material
                String apellido = entry.getStringValue(3).toLowerCase(); // Columna de tipo

                // Verificar si alguno de los valores contiene el texto de búsqueda
                return nombre.contains(searchText) || apellido.contains(searchText);
            }
        });
    

    }

    // Si no se encontró ninguna coincidencia, puedes mostrar un mensaje o realizar otra acción
    if (jTable1.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "No se encontraron resultados.");
    }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Crear un array para almacenar los datos
        String[] datos = new String[4];

        // Pedir al usuario que ingrese los datos
        datos[0] = JOptionPane.showInputDialog(this, "Ingrese el Nombre:");
        datos[1] = JOptionPane.showInputDialog(this, "Ingrese la Apellido:");
        datos[2] = JOptionPane.showInputDialog(this, "Ingrese la Telefono:");
        datos[3] = JOptionPane.showInputDialog(this, "Ingrese la Dirección:");

        // Validar que los campos no estén vacíos
        for (String dato : datos) {
            if (dato == null || dato.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // Generar un ID aleatorio de 4 cifras
        int newId;
        do {
            newId = generateRandomId(5); // Cambia el número de cifras aquí si es necesario
        } while (idExists(newId)); // Verifica que el ID no se repita

        // Agregar los datos a la tabla
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int rowCount = model.getRowCount(); // Obtener el número actual de filas
        Object[] rowData = {rowCount + 1, newId, datos[0], datos[1], datos[2],datos[3]}; // Asignar el número de fila
        model.addRow(rowData);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // Obtener el modelo de la tabla
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Obtener los índices de las filas seleccionadas
    int[] selectedRows = jTable1.getSelectedRows();

    // Verificar si se ha seleccionado alguna fila
    if (selectedRows.length > 0) {
        // Eliminar las filas seleccionadas en orden inverso
        for (int i = selectedRows.length - 1; i >= 0; i--) {
            model.removeRow(selectedRows[i]);
        }

        // Actualizar la numeración de la columna #
        for (int i = 0; i < model.getRowCount(); i++) {
            model.setValueAt(i + 1, i, 0); // Actualiza la columna # (índice 0)
        }

        // Mostrar un mensaje de confirmación
        JOptionPane.showMessageDialog(this, "Eliminados correctamente.", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
    } else {
        // Si no hay filas seleccionadas, mostrar un mensaje de advertencia
        JOptionPane.showMessageDialog(this, "Por favor, selecciona al menos un registro para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }

    }//GEN-LAST:event_jButton12ActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        int posicion = this.jPanel3.getX();
        if(posicion>-1){
            Animacion.Animacion.mover_izquierda(0,-258,2, 2, jPanel3);
        }else{
            Animacion.Animacion.mover_derecha(-258,0,2,2,jPanel3);
        }
    }//GEN-LAST:event_menuActionPerformed

    private void rSButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButton2ActionPerformed

    private void rSButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButton3ActionPerformed

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unoActionPerformed

    private void rSButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButton4ActionPerformed

    private void rSButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton5ActionPerformed
        clientes db = new clientes();
        db.setVisible(true);
        dispose();
    }//GEN-LAST:event_rSButton5ActionPerformed

    private void rSButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButton6ActionPerformed

    private void rSButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButton7ActionPerformed

    private void rSButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private rojeru_san.RSButton menu;
    private rojeru_san.RSButton rSButton2;
    private rojeru_san.RSButton rSButton3;
    private rojeru_san.RSButton rSButton4;
    private rojeru_san.RSButton rSButton5;
    private rojeru_san.RSButton rSButton6;
    private rojeru_san.RSButton rSButton7;
    private rojeru_san.RSButton rSButton8;
    private rojeru_san.RSButton uno;
    // End of variables declaration//GEN-END:variables

    private int generateRandomId(int digits) {
    Random random = new Random();
    int lowerBound = (int) Math.pow(10, digits - 1); // 10^(n-1)
    int upperBound = (int) Math.pow(10, digits) - 1; // 10^n - 1
    return random.nextInt(upperBound - lowerBound + 1) + lowerBound;
}

    private boolean idExists(int id) {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    for (int i = 0; i < model.getRowCount(); i++) {
        if ((Integer) model.getValueAt(i, 0) == id) { // Asegúrate de que estás verificando la columna correcta
            return true; // El ID ya existe
        }
    }
    return false; // El ID no existe
    }
}
